import re

with open('src/swiftdrop/cli.py', 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "棕仙的传输软件命令行接口": "Zongxian Transfer CLI",
    "发现局域网设备": "Discover LAN devices",
    "覆盖数据端口（默认": "Override data port (default",
    "本端接收分片大小（MB，默认 4）": "Receive chunk size in MB (default 4)",
    "对外显示的设备名": "Device name to display",
    "允许对端要求删除多余文件（同步用）": "Allow remote to request deletion of extra files (for sync)",
    "被动同步目录（默认同 --dir）": "Passive sync directory (default same as --dir)",
    "接收文件/等待被同步": "Receive files / wait to be synced",
    "发送文件/文件夹": "Send file/folder",
    "一个或多个文件/目录": "One or more files/directories",
    "覆盖数据端口": "Override data port",
    "并发流数 1-8（默认按到目标的延迟自动选：局域网": "Concurrent streams 1-8 (default auto based on latency: LAN",
    "条、": " streams, ",
    "跨网/异地组网最多 8 条）": "remote max 8 streams)",
    "单文件重试次数": "Single file retry count",
    "分片大小（MB，默认 4）": "Chunk size in MB (default 4)",
    "设备名解析超时": "Device name resolution timeout",
    "本机显示名": "Local display name",
    "ip、ip:端口 或设备名": "ip, ip:port or device name",
    "目录同步": "Directory sync",
    "本地目录": "Local directory",
    "双向同步（默认）": "Two-way sync (default)",
    "单向：本地覆盖远端": "One-way: local overrides remote",
    "删除另一边没有的文件（默认关）": "Delete files missing on the other side (default off)",
    "持续监控同步": "Continuous watch sync",
    "监控轮询秒数": "Watch poll interval in seconds",
    "并发流数": "Concurrent streams",
    "覆盖数据端口": "Override data port",
    "不启动本机接收端（纯推送模式）": "Do not start local receiver (pure push mode)",
    "局域网静态服务 + 信令中继": "LAN static server + signaling relay",
    "根目录（默认 dist 或当前目录）": "Root dir (default dist or current dir)",
    "端口（默认 8787）": "Port (default 8787)",
    "首页 html 文件路径": "Index html file path",
    "跨网传输：内置网页版窗口（用系统 Edge/Chrome 作内核）": "Cross-network transfer: built-in web app window (uses system Edge/Chrome)",
    "网页版所在目录（默认 dist 或当前目录）": "Web app directory (default dist or current dir)",
    "内置服务端口（默认 8787）": "Built-in server port (default 8787)",
    "窗口宽（默认 1220）": "Window width (default 1220)",
    "窗口高（默认 880）": "Window height (default 880)",
    "用你当前浏览器的配置打开（默认用独立配置，不干扰你自己的浏览器）": "Open with your current browser profile (default uses independent profile)",
    "尝试无地址栏的应用窗口（默认交给系统默认浏览器打开，最稳）": "Try frameless app window (default uses system default browser)",
    "少打印日志": "Print less logs",
    "WebSocket 信令中继（默认端口 8788）": "WebSocket signaling relay (default port 8788)",
    "端口（默认 8788）": "Port (default 8788)",
    "打印每条中继日志": "Print every relay log",
    "开机自启的无界面同步守护进程": "Headless sync daemon on startup",
    "隐藏控制台黑窗口（开机自启命令用的就是这个）": "Hide console window (used for autostart)",
    "日志同时打到控制台": "Log to console as well",
    "覆盖配置里的轮询秒数（调试用）": "Override poll interval in config (for debugging)",
    "设备名解析超时秒数": "Device name resolution timeout in seconds",
    "只打印配置与自启状态，然后退出": "Print config and autostart status, then exit",
    "每个文件夹只跑一轮就退出（调试/自测用）": "Run one pass per folder then exit (for testing)",
    "开机自启开关（注册表 Run 项）": "Autostart switch (registry Run key)",
    "on=开启 / off=关闭 / status=查看": "on=enable / off=disable / status=view",
    "管理开机同步的文件夹": "Manage folders for autostart sync",
    "登记一个同步文件夹": "Register a sync folder",
    "本地文件夹路径": "Local folder path",
    "对端设备名（局域网发现用）": "Peer device name (for LAN discovery)",
    "对端 IP（跳过设备发现）": "Peer IP (skip discovery)",
    "对端数据端口": "Peer data port",
    "轮询秒数（默认 5）": "Poll interval (default 5)",
    "不改文件夹图标": "Do not change folder icon",
    "只登记文件夹，不动开机自启": "Only register folder, do not touch autostart",
    "取消登记一个同步文件夹": "Unregister a sync folder",
    "保留文件夹图标标记": "Keep folder icon mark",
    "列出已登记的文件夹": "List registered folders",
    "输出 JSON（给自动化用）": "Output JSON (for automation)",
    "保存目录（默认当前目录）": "Save directory (default current dir)",
    "覆盖数据端口（默认": "Override data port (default",
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open('src/swiftdrop/cli.py', 'w', encoding='utf-8') as f:
    f.write(text)
